#!/bin/bash


echo -e "what do you want to see ?
today's date (d)
Current logged in user (u)
the content of $PWD (c)
enter your choice (d/u/c) --> \c "

read answer

if [ $answer = "d" ]; then
	echo `date`
elif test $answer = u ; then
echo `whoami`

elif [ $answer = "c" ]; then
ls -a

else
echo -e "the option wasnt correct"

fi
